#!/usr/bin/env python
# Generated by jaraco.develop (https://bitbucket.org/jaraco/jaraco.develop)
setup_params = dict(
	name='excuses',
	use_hg_version=True,
	py_modules=['excuses'],
	data_files=[
		('', ['excuses.txt', 'excuses.html']),
	],
	zip_safe=False,
	setup_requires=[
		'hgtools',
	],
	entry_points = dict(
		console_scripts = [
			'serve-excuses = excuses:main',
		],
		pmxbot_handlers = [
			'dowski-excuses = excuses:RandomExcuseGenerator.install_pmxbot_command',
		],
	),
)
if __name__ == '__main__':
	from setuptools import setup
	setup(**setup_params)
