#!/usr/bin/env python
# Generated by jaraco.develop (https://bitbucket.org/jaraco/jaraco.develop)
setup_params = dict(
	name='excuses',
	use_hg_version=True,
	py_modules=['excuses'],
	data_files=[
		('', ['excuses.txt', 'excuses.html']),
	],
	zip_safe=False,
	setup_requires=[
		'hgtools',
	],
)
if __name__ == '__main__':
	from setuptools import setup
	setup(**setup_params)
