#!/usr/bin/env python
# Generated by jaraco.develop (https://bitbucket.org/jaraco/jaraco.develop)

import sys

import setuptools

py26_reqs = ['argparse'] if sys.version_info < (2, 7) else []

setup_params = dict(
	name='excuses',
	use_hg_version=True,
	include_package_data=True,
	packages=setuptools.find_packages(),
	install_requires=py26_reqs,
	setup_requires=[
		'hgtools',
	],
	entry_points = dict(
		console_scripts = [
			'serve-excuses = excuses:main',
		],
		pmxbot_handlers = [
			'dowski excuses = excuses:RandomExcuseGenerator.install_pmxbot_command',
		],
	),
)
if __name__ == '__main__':
	setuptools.setup(**setup_params)
